### ISSUE TITLE
Plugin sets modifiable for buffer which plugin is attached to

### ISSUE THREAD

**Issue by afterlook** [crusj/structrue-go.nvim#2]
When function `tags.flush_to_bufs()` is executed, it sets my current file buffer state to false.

I guess the intended purpose was to specific some target buffer, but on my environment it does that to whatever structure is attached to.

How to reproduce:
1. open file
2. toggle structure
3. <c-p> on anything
4. <\\-p> to exit
5. switch to file
6. voila, modifiable set to false

**Comment by crusj** [comment]
> When function `tags.flush_to_bufs()` is executed, it sets my current file buffer state to false.
> 
> I guess the intended purpose was to specific some target buffer, but on my environment it does that to whatever structure is attached to.
> 
> How to reproduce:
> 
> 1. open file
> 2. toggle structure
> 3. on anything
> 4. <\-p> to exit
> 5. switch to file
> 6. voila, modifiable set to false
Fixed it.

**Comment by crusj** [comment]
> When function `tags.flush_to_bufs()` is executed, it sets my current file buffer state to false.
> 
> I guess the intended purpose was to specific some target buffer, but on my environment it does that to whatever structure is attached to.
> 
> How to reproduce:
> 
> 1. open file
> 2. toggle structure
> 3. on anything
> 4. <\-p> to exit
> 5. switch to file
> 6. voila, modifiable set to false

Fixed it.

**Comment by afterlook** [comment]
Just checked, change broke preview functionality.

**Comment by crusj** [comment]
> Just checked, change broke preview functionality.

I checked that the preview is available, I just turned off the modifiable option of the preview buffer

**Comment by afterlook** [comment]
Noticed It did happen only once for now. I'll keep an eye on this and try to get fully reproducible example.

I'm sure there is something to it as an error was about modifiable flag when trying to go to preview.
